### ISSUE TITLE
[FEATURE] EDT salle

### ISSUE THREAD

**Issue by eliott-b** [Escartem/EDTVelizy#1]
Ca serait bien d'avoir accès à l'EDT des salles comme sur l'officiel.

**Comment by Escartem** [comment]
![image](https://github.com/user-attachments/assets/e977caa3-fc66-4374-a411-18d6a6e5714a)
comme ca ?
si c'est juste ca, ca peut se rajouter facilement oui

**Comment by Escartem** [comment]
@Eliott-B ajouté (9cdf0405749db4dc82de713ababb88852b4d1700) 👍
