### ISSUE TITLE
[BUG] La salle se retrouve dans le champs du prof

### ISSUE THREAD

**Issue by eliott-b** [Escartem/EDTVelizy#2]
L'Amphi A se retrouve dans le champ des intervenants et la salle 414 n'apparait pas.  
_Cours de 13h30 à 15h30 le Vendredi 25/10/24 pour les INF3-FA._   
<img width="286" alt="Screenshot 2024-10-22 at 22 14 34" src="https://github.com/user-attachments/assets/dd8f270d-216b-45bf-b7de-aa77218e148e">
<img width="326" alt="Screenshot 2024-10-22 at 22 14 42" src="https://github.com/user-attachments/assets/b5285794-7755-4874-b10d-00328a79ef0a">

**Comment by Escartem** [comment]
C'est vraiment mal fait celat, ils envoient les données n'importe comment. C'est corrigé maintenant (4c47a71a3b633c83ff597ee751feb579f1d2af2b), et j'en ai profité pour afficher les remarques de cours en plus 🎉
